#!/usr/bin/ruby

ALPHABET = [*("a".."z"), *("1".."9"), " "]
STRICT_ALPHABET = [*("a".."z"), *("A".."Z"), *("1".."9"), " ", "!", "@", "#", "$", "%", "^", "&", "*", "(", ")", "-", "_", "+", "=", "{", "}", "[", "]", "|", "\\", '<', '>', '.', ',', '?', '/']

if File.file?(File.join(File.dirname(__FILE__), 'encryption.rb'))
  require_relative 'encryption.rb'
else
  require '/usr/share/ruby/vendor_ruby/coder/encryption.rb'
end
require 'optparse'

class String
  def clean_newlines sub = '[newline]'
    replace gsub "\n", sub
  end
end

options = {
  method: :encrypt,
  text: "example text",
  strict: false,
  key: "examplekey"
}

OptionParser.new do |parser|
  parser.banner = "Usage: coder [options]"

  parser.on("-h", "--help", "Show this help message") do
    puts parser
    exit
  end

  parser.on("-e", "--encrypt", "Encrypts text (default)") do
  end

  parser.on("-d", "--decrypt", "Decrypts text") do
    options[:method] = :decrypt
  end
  
  parser.on("-t", "--text TEXT", "The text to encrypt or decrypt") do |v|
    options[:text] = v
  end
  
  parser.on("-f", "--file PATH", "Encrypt or decrypt a file instead") do |v|
    unless File.file? v
      puts "The path you entered does not exist or is not a file."
      exit
    end
    options[:file] = v
  end

  parser.on("-k", "--key KEY", "Specify a key to use") do |v|
    options[:key] = v
  end

  parser.on("-s", "--strict", "Keeps capital letters and encrypts punctuation") do
    options[:strict] = true
  end

  parser.on("-o", "--output PATH", "Specify a file to export the result of the encryption or decryption to") do |v|
    options[:output] = v
  end
end.parse!

def check_key k, a
  k.chars.each do |char|
    return false unless a.include? char
  end
  true
end

o = options[:output]
f = options[:file]
t = options[:text]
t = File.read f if f
t_display = f ? f : t

k = options[:key]
e = options[:method] == :encrypt
s = options[:strict]
a = s ? STRICT_ALPHABET : ALPHABET

unless check_key k, a
  puts "The key that you entered is invalid! Please use only the following characters: "
  puts a.map {|char| "'#{char}'"}.join(", ") + "."
  puts "NOTE: If you are trying to use capitals or punctuation, you may want to try strict mode (--strict or -s)."
  exit
end

m_text = e ? "encrypted" : "decrypted"
e_text = t.encrypt k, a, s, !e
display_e_text = o ? o : e_text

if display_e_text.length + t_display.length < 50
  t.clean_newlines
  e_text.clean_newlines
  line = "-" * (t_display.length+2) + "=" * (display_e_text.length+1)
  puts line
  puts "#{t_display} ➜ #{display_e_text}"
  puts line
  puts
  puts (f ? "The contents of " : "The text ") + "\"#{t_display}\" was #{m_text} to \"#{display_e_text}\" using key: \"#{k}\""
else
  puts
  puts t_display
  puts
  puts
  puts display_e_text
  puts
end

File.new(o, "w").write e_text if o
